# Generated by Django 4.1 on 2023-01-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "good",
                    models.CharField(default="", max_length=50, verbose_name="商品名称"),
                ),
                (
                    "brand",
                    models.CharField(default="", max_length=50, verbose_name="品牌型号"),
                ),
                ("unit", models.IntegerField(default=0, verbose_name="单位")),
                ("quantity", models.IntegerField(default=0, verbose_name="数量")),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="姓名"),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=50, verbose_name="联系电话"),
                ),
                (
                    "num",
                    models.CharField(default="", max_length=50, verbose_name="课题编号"),
                ),
                (
                    "info",
                    models.CharField(default="", max_length=20, verbose_name="采购说明"),
                ),
                (
                    "detail",
                    models.CharField(default="", max_length=100, verbose_name="商品编号"),
                ),
                (
                    "group",
                    models.CharField(default="", max_length=50, verbose_name="单位全称"),
                ),
                ("date", models.DateField(verbose_name="提交时间")),
                ("finish", models.BooleanField(default=0, verbose_name="是否完成")),
            ],
        ),
        migrations.CreateModel(
            name="ItemLog",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="操作编号"
                    ),
                ),
                (
                    "ip",
                    models.CharField(default="", max_length=50, verbose_name="操作ip"),
                ),
                ("date", models.DateTimeField(verbose_name="操作时间")),
                (
                    "cmd",
                    models.CharField(default="", max_length=50, verbose_name="操作类型"),
                ),
                (
                    "other",
                    models.CharField(default="", max_length=70, verbose_name="备注"),
                ),
            ],
        ),
    ]
