# Generated by Django 4.1 on 2023-01-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyitem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="date",
            field=models.DateField(verbose_name="提交日期"),
        ),
    ]
