# Generated by Django 4.1 on 2023-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyitem", "0003_alter_item_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="classif",
            field=models.CharField(default="", max_length=30, verbose_name="物资分类"),
        ),
    ]
