# Generated by Django 4.1 on 2023-01-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyitem", "0005_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="finish",
            field=models.BooleanField(default=False, verbose_name="是否完成"),
        ),
    ]
