# Generated by Django 4.1 on 2023-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyitem", "0006_suggestion_finish"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="company",
            field=models.CharField(default="", max_length=50, verbose_name="公司"),
        ),
    ]
