# Generated by Django 4.1 on 2023-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SOFCTest",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("grp", models.IntegerField(default=0, verbose_name="实验组")),
                ("ns", models.IntegerField(default=0, verbose_name="电池数量")),
                (
                    "gas",
                    models.CharField(default="H2", max_length=50, verbose_name="气体名称"),
                ),
                (
                    "tmp",
                    models.DecimalField(
                        decimal_places=2,
                        default=298.15,
                        max_digits=5,
                        verbose_name="温度",
                    ),
                ),
                ("prs", models.IntegerField(default=101325, verbose_name="压力")),
                (
                    "curv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="输入流量"
                    ),
                ),
                (
                    "cure",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="输入电流"
                    ),
                ),
                (
                    "vlt",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="输入电压"
                    ),
                ),
            ],
        ),
    ]
