# Generated by Django 4.1.4 on 2022-12-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='项目名称')),
                ('date', models.DateField(verbose_name='起始时间')),
                ('enddate', models.DateField(verbose_name='完成时间')),
                ('group', models.CharField(default='', max_length=50, verbose_name='项目组名称')),
                ('person', models.CharField(default='', max_length=50, verbose_name='完成人')),
                ('classification', models.CharField(default='', max_length=20, verbose_name='项目类别')),
                ('finish', models.BooleanField(default=False, verbose_name='是否完成')),
            ],
        ),
    ]
