# Generated by Django 4.1.4 on 2022-12-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='项目编号'),
        ),
    ]
