# Generated by Django 4.1.4 on 2023-01-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='date',
            field=models.DateTimeField(verbose_name='操作时间'),
        ),
    ]
